--- 
- hosts: all
  name: "install the iis web service"
  tasks: 
    - name: "install iis"
      win_feature: 
        name: Web-Server
        state: present
    - name: "start iis service"
      win_service: 
        name: W5Svc
        state: started
    - name: "Create website index.html"
      win_copy: 
        content: "<html><body><h1>Our webiste is now alive!</h1></body></html>"
        dest: "C:\\Ansible testing\\IIS Webserver\\index.html"    
